services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./render-build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: dpg-d02acdruibrs73am8hg0-a
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: e2b27fcdf02a8a9965433775839c09da
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: e2b27fcdf02a8a9965433775839c09da_user
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rt2pZBhl0C3t2DJqRtdTtyTyQMCbG2Zt
          property: password
