services:
  - type: web
    name: laravel-app
    env: php
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    deployCommand: php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: SESSION_DRIVER
        value: database
      - key: DB_CONNECTION
        value: pgsql  # or mysql depending on your database
      - key: DATABASE_URL
        value: postgresql://e2b27fcdf02a8a9965433775839c09da_user:rt2pZBhl0C3t2DJqRtdTtyTyQMCbG2Zt@dpg-d02acdruibrs73am8hg0-a/e2b27fcdf02a8a9965433775839c09da
